#!/usr/bin/env python3
"""Regenerate src/romdata.js from the ROM dumps embedded in floooh/pacman.c.

The arcade board's artwork, colours and sound waveforms live in ROMs and PROMs
that are not reproducible from documentation — they are data, not algorithms.
Andre Weissflog's pacman.c (MIT, https://github.com/floooh/pacman.c) carries
them as plain C arrays, which is where we take them from.

    git clone --depth 1 https://github.com/floooh/pacman.c /tmp/pacman.c
    python3 tools/extract-rom-data.py /tmp/pacman.c/pacman.c

What is extracted, and what each blob is on the real board:

    rom_tiles[4096]     pacman.5e   256 background tiles, 8x8, 2bpp
    rom_sprites[4096]   pacman.5f   64 sprites, 16x16, 2bpp
    rom_hwcolors[32]    82s123.7f   colour PROM, one packed RGB byte per entry
    rom_palette[256]    82s126.4a   palette PROM, 64 colour codes of 4 pens
    rom_wavetable[256]  82s126.1m   Namco WSG, 8 waveforms of 32 4-bit samples

Plus two captures of the sound chip's register writes, which is how the two
tunes are reproduced without transcribing the music itself:

    snd_dump_prelude[490]   start-of-round tune, voices 0+1, 245 ticks
    snd_dump_dead[90]       death sound, voice 2, 90 ticks
"""

import base64
import re
import sys
from pathlib import Path

BYTE_ARRAYS = [
    ('TILE_ROM', 'rom_tiles', 4096),
    ('SPRITE_ROM', 'rom_sprites', 4096),
    ('HW_COLORS', 'rom_hwcolors', 32),
    ('PALETTE_PROM', 'rom_palette', 256),
    ('WAVETABLE', 'rom_wavetable', 256),
]

WORD_ARRAYS = [
    ('SND_PRELUDE', 'snd_dump_prelude', 490),
    ('SND_DEAD', 'snd_dump_dead', 90),
]


def read_array(source, c_name, kind, expected):
    """Pull one `static const <kind> <c_name>[N] = { ... };` array out of the C source."""
    pattern = r'static const %s %s\[\d+\] = \{' % (kind, c_name)
    match = re.search(pattern, source)
    if not match:
        raise SystemExit('could not find %s in the source file' % c_name)
    # Scan forward to the closing brace rather than regexing across it: the
    # bodies are thousands of entries long and contain no nested braces.
    end = source.index('};', match.end())
    values = [int(v, 16) for v in re.findall(r'0[xX][0-9A-Fa-f]+', source[match.end():end])]
    if len(values) != expected:
        raise SystemExit('%s: expected %d entries, found %d' % (c_name, expected, len(values)))
    return values


def as_base64(values, bytes_per_value):
    raw = bytearray()
    for v in values:
        raw += v.to_bytes(bytes_per_value, 'little')
    return base64.b64encode(bytes(raw)).decode('ascii')


def wrap(text, width=96):
    """Split a base64 blob into concatenated string literals so lines stay readable."""
    chunks = [text[i:i + width] for i in range(0, len(text), width)]
    return '\n'.join("  '%s'%s" % (c, '' if i == len(chunks) - 1 else ' +')
                     for i, c in enumerate(chunks))


def main():
    if len(sys.argv) != 2:
        raise SystemExit('usage: extract-rom-data.py <path to floooh pacman.c>')
    source = Path(sys.argv[1]).read_text()

    out = ["""// Generated by tools/extract-rom-data.py — do not edit by hand.
//
// ROM and PROM contents from the 1980 Namco Pac-Man board, taken from the
// dumps embedded in floooh/pacman.c (MIT). These are data the board reads,
// not code: the artwork, the colour ladder and the sound chip's waveforms.
// Everything is base64 of the raw bytes so the arrays stay byte-exact.
//
//   TILE_ROM      pacman.5e   256 background tiles, 8x8, 2 bits per pixel
//   SPRITE_ROM    pacman.5f   64 sprites, 16x16, 2 bits per pixel
//   HW_COLORS     82s123.7f   32 colours, packed as |B1|B0|G2|G1|G0|R2|R1|R0|
//   PALETTE_PROM  82s126.4a   64 colour codes of 4 pens each
//   WAVETABLE     82s126.1m   Namco WSG: 8 waveforms of 32 4-bit samples
//
// SND_PRELUDE and SND_DEAD are captures of the sound chip's register writes,
// one 32-bit word per voice per 60Hz tick:
//   bits 0-19 frequency, bits 24-26 waveform, bits 28-31 volume.
//
// PAC-MAN is a trademark of Bandai Namco. This project is an unofficial
// tribute; see README.md.

function bytes(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function words(b64) {
  const raw = bytes(b64);
  return new Uint32Array(raw.buffer, raw.byteOffset, raw.length / 4);
}
"""]

    for js_name, c_name, expected in BYTE_ARRAYS:
        values = read_array(source, c_name, 'uint8_t', expected)
        out.append('export const %s = /* %s */ bytes(\n%s,\n);\n'
                   % (js_name, c_name, wrap(as_base64(values, 1))))

    for js_name, c_name, expected in WORD_ARRAYS:
        values = read_array(source, c_name, 'uint32_t', expected)
        out.append('export const %s = /* %s */ words(\n%s,\n);\n'
                   % (js_name, c_name, wrap(as_base64(values, 4))))

    target = Path(__file__).resolve().parent.parent / 'src' / 'romdata.js'
    target.write_text('\n'.join(out))
    print('wrote %s (%d bytes)' % (target, target.stat().st_size))


if __name__ == '__main__':
    main()
